BBPATH .= ":${LAYERDIR}"

BBFILES += " \
${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILES_DYNAMIC += " \
    petalinux:${LAYERDIR}/dynamic-layers/meta-petalinux/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "enclustra-lab"
BBFILE_PATTERN_enclustra-lab = "^${LAYERDIR}/"
BBFILE_PRIORITY_enclustra-lab = "20"
BBFILE_PATTERN_IGNORE_EMPTY_enclustra-lab = "1"
LAYERVERSION = "1"
LAYERSERIES_COMPAT_enclustra-lab = "kirkstone langdale scarthgap"
