BBPATH .= ":${LAYERDIR}"

BBFILES += " \
${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILES_DYNAMIC += " \
    petalinux:${LAYERDIR}/dynamic-layers/meta-petalinux/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "enclustra-refdes"
BBFILE_PATTERN_enclustra-refdes = "^${LAYERDIR}/"
BBFILE_PRIORITY_enclustra-refdes = "20"
BBFILE_PATTERN_IGNORE_EMPTY_enclustra-refdes = "1"
LAYERVERSION = "1"
LAYERSERIES_COMPAT_enclustra-refdes = "scarthgap"
