BBPATH .= ":${LAYERDIR}"

BBFILES += " \
${LAYERDIR}/recipes-*/*/*.bb \
${LAYERDIR}/recipes-*/*/*.bbappend \
"

YOCTOROOT = "${@os.path.abspath(os.path.join("${TOPDIR}", os.pardir))}"

BBFILES_DYNAMIC += " \
${@bb.utils.contains("BBLAYERS", "${YOCTOROOT}/meta-enclustra-refdes", "","xilinx:${LAYERDIR}/dynamic-layers/meta-enclustra-nopl/recipes-*/*/*.bb", d)} \
${@bb.utils.contains("BBLAYERS", "${YOCTOROOT}/meta-enclustra-refdes", "","xilinx:${LAYERDIR}/dynamic-layers/meta-enclustra-nopl/recipes-*/*/*.bbappend", d)} \
"

BBFILE_COLLECTIONS += "enclustra-module"
BBFILE_PATTERN_enclustra-module = "^${LAYERDIR}/"
BBFILE_PRIORITY_enclustra-module = "10"
BBFILE_PATTERN_IGNORE_EMPTY_enclustra-module = "1"

LAYERVERSION = "1"
LAYERSERIES_COMPAT_enclustra-module = "scarthgap"
LAYERDEPENDS_enclustra-module = "xilinx xilinx-multimedia"
